<?php require_once 'templates/header.phtml'?>

<form action="authentic" method="POST">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email</label>
    <input name= "email" type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">nunca compartiremos tu información con nadie</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input name= "password" type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
<div class="login-error-box">
  <p class="login-error">Contraseña incorrecta, vuelva a intentar</p>
</div>

<?php require_once 'templates/footer.phtml'?>