
<?php require_once 'templates/header.phtml'?>

    <div class="card" style="width: 18rem;">
        <?php if (isset($detail->img)): ?>
            <img src="imagenes/<?= $detail->img ?>" class="imgTable" alt="imagen de un objeto">
        <?php endif;?>
        <div class="card-body">
            <?php if(isset($detail->tipo_item) && isset($detail->condicion)) : ?>
                <h5 class="card-title"><?= $detail->tipo_item?></h5>
                <p class="card-text"><?= $detail->condicion?></p>
            <?php endif;?>
                <a href="mostrarObjetos" class="btn btn-primary">Volver</a>
        </div>
    </div>

<?php require_once 'templates/footer.phtml'?>