<?php require_once 'templates/header.phtml'?>

<div class="container">
    <h1>Editar este item</h1>
    <form action="editarItem/<?=$item->id_item?>" method="POST">
        <div class="mb-3">
            <label for="type" class="form-label">Tipo:</label>
            <select class="form-select" id="type" name="type" value="<?= $item->tipo_item?>" required>
            <option value="">Selecciona un tipo de item</option>
            <option value="termo">termo</option>
            <option value="mate">mate</option>
            <option value="calculadora">calculadora</option>
            </select>
        </div>
        <div class="mb-3">
            <label for="number" class="form-label">numero:</label>
            <input type="number" class="form-control" id="number" name="number" value="<?= $item->numero_item?>" required>
        </div>
        <div class="mb-3">
            <label for="state" class="form-label">En que estado esta:</label>
            <input type="text" class="form-control" id="state" name="state" value="<?= $item->condicion?>" required>
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>

<?php require_once 'templates/footer.phtml'?>