
<?php require_once 'templates/header.phtml';?>
<table class="table">
    <thead class="table-dark">
        <?php if(isset($name)) : ?>
            <h1><?=$name->nombre?></h1>
        <?php endif;?>
        <tr>          
            <th scope="col">imagen</th>
            <th scope="col">tipo</th>
            <th scope="col">numero</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($filterStudent as $itemStudents) : ?>
            <tr>
                <td>
                    <?php if (isset($itemStudents->img)): ?>
                        <img src="imagenes/<?= $itemStudents->img ?>" class="imgTable">
                    <?php endif;?>        
                </td>              
                <td><?= $itemStudents->tipo_item?></td>
                <td><?= $itemStudents->numero_item?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>