</main>


<div class="footer-content">
  <div class="footer-body">
    <p class="footer-text">AMU CONDUCCIÓN |</p>
    <img class="amu-logo" src="./imagenes/logoAMU.png" alt="Esta es una imagen">
    <a class="amu-link" href="https://www.instagram.com/amu.mpe.exactas/" target="_blank">@amu.mpe.exactas</a>
  </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>