<!DOCTYPE html>
<html lang="en">
  <head>
    <base href="{BASE_URL}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./app/views/css/style.css">
    <title>CEFCE</title>
    
  </head>
  <body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbarStyle" >
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarColor01">     
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">          
                <li class="nav-item">
                    <a class="nav-link" href="showDiscography">ahahahah</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="showRecords">jahajshjahd</a>
                </li>
                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Categoria
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                        {foreach from=$records item=$record}
                            <li><a class="dropdown-item" href="filter/{$record->fk_records_id}">{$record->records}</a></li>
                        {/foreach}
                        </ul>
                        </li>
                    </ul>
                    </div>
                </div>
                </ul> 
            </div>
        </div>
        </nav>
  
  </header>
   
  <main class="container">