<!DOCTYPE html>
<html lang="en">
  <head>
    <base href="{BASE_URL}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>CEFCE</title>
    
  </head>
  <body>
    <header>
        <img src="imagenes/DSC_0760.jpg" alt="Gallito campeon">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbarStyle" >
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarColor01">     
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">          
                <li class="nav-item">
                    <a class="nav-link" href="mostrarObjetos">todos los objetos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="mostarAlumnos">Listado de alumnos que pidieron algo</a>
                </li>
                <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Alumnos
                        </a>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <?php foreach($students as $student) : ?>
                                <li><a class="dropdown-item" href="filtro/<?= $student->id_alumno;?>"><?=$student->nombre?></a></li>
                            <?php endforeach;?>
                        </ul>
                        </li>
                    </ul>
                    </div>
                </div>
                </ul> 
            </div>
        </div>
        </nav>
    </header>
   
  <main class="container">