
<?php require_once 'templates/header.phtml'?>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">nombre</th>
            <th scope="col">apellido</th>
            <th scope="col">numero de celular</th>
            <th scope="col">DNI</th>
            <th scope="col">fecha de prestamo</th>
            <?php if (isset($_SESSION['ID_USER'])) : ?>
                <th scope="col">editar/borrar</th>
            <?php endif ?>
        </tr>
    </thead>

    <tbody>
        <?php foreach($students as $student) : ?>
            <tr>               
                <td><?= $student->nombre?></td>
                <td><?= $student->apellido?></td>
                <td><?= $student->numero_celular?></td>
                <td><?= $student->dni?></td>
                <td><?= $student->fecha_dia?></td>
                <?php if (isset($_SESSION['ID_USER'])) : ?>
                    <td>
                        <a href="mostrarEdicionDeEStudiante/<?= $student->id_alumno ?>" type="button" class='btn btn-success ml-auto'>Editar</a>
                        <a href="eliminarEstudiante/<?= $student->id_alumno?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                    </td>
                <?php endif ?>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>

<?php if (isset($_SESSION['ID_USER'])) : ?>
    <?php require_once 'templates/form.student.phtml'?>
<?php endif ?>

<?php require_once 'templates/footer.phtml'?>