<?php require_once 'templates/header.phtml';?>

<div class="title-box">
    <h1 class="title">Objetos para prestar</h1>
</div>


<table class="table table-hover">
    <thead>
        <tr >
            <th scope="col">imagen</th>
            <th scope="col">tipo</th>
            <th scope="col">numero</th>
            <th scope="col">esta prestado</th>
            <th scope="col">en que condicion que esta</th>
            <th scope="col">estado</th>
            <?php if (isset($_SESSION['ID_USER'])) : ?>
                <th scope="col">editar/borrar</th>
            <?php endif ?>
        </tr>
    </thead>

    <tbody>
        <?php foreach($items as $item) : ?>
            <tr>
                <td>
                    <a href="detalle/<?= $item->id_item?>">
                        <?php if (isset($item->img)): ?>
                            <img src="imagenes/<?= $item->img ?>" class="imgTable">
                        <?php endif;?>
                    </a>        
                </td>               
                <td><?= $item->tipo_item?></td>
                <td><?= $item->numero_item?></td>
                <?php if($item->en_uso): ?>
                    <td>Prestado</td>
                <?php else : ?>
                    <td>No esta Prestado</td>
                <?php endif;?>
                <td><?= $item->condicion?></td>
                <td>
                <?php if(!$item->en_uso): ?>
                        <a href="prestarEstudiante/<?= $item->id_item ?>" type="button" class='btn btn-exa'>Prestar</a>
                    <?php else : ?>
                        <a href="devolverItem/<?= $item->id_item?>" type="button" class='btn btn-exa'>Devolver</a>
                    <?php endif;?>
                </td>
                <?php if (isset($_SESSION['ID_USER'])) : ?>
                    <td>
                        <a href="mostrarEdicionItem/<?=$item->id_item?>" type="button" class='btn btn-success ml-auto'>Editar</a>
                        <a href="eliminar/<?= $item->id_item ?>" type="button" class='btn btn-danger ml-auto'>Borrar</a>
                    </td>
                <?php endif ?>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>

<?php if (isset($_SESSION['ID_USER'])) : ?>
    <?php require_once 'templates/form.item.phtml';?>
<?php endif ?>

<?php require_once 'templates/footer.phtml' ?>