<?php require_once 'templates/header.phtml';?>
<?php require_once 'templates/form.item.phtml';?>


<h1 class="title">Objetos para prestar</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">imagen</th>
            <th scope="col">id</th>
            <th scope="col">tipo</th>
            <th scope="col">numero</th>
            <th scope="col">esta prestado</th>
            <th scope="col">en que condicion que esta</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach($items as $item) : ?>
            <tr>
                <td>
                    <a href="detalle/<?= $item->id_item?>">
                        <?php if (isset($item->img)): ?>
                            <img src="imagenes/<?= $item->img ?>" class="imgTable">
                        <?php endif;?>
                    </a>        
                </td>
                <td><?= $item->id_item?></td>                
                <td><?= $item->tipo_item?></td>
                <td><?= $item->numero_item?></td>
                <?php if($item->en_uso): ?>
                    <td>Prestado</td>
                <?php else : ?>
                    <td>No esta Prestado</td>
                <?php endif;?>
                <td><?= $item->condicion?></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
  
<?php require_once 'templates/footer.phtml' ?>